# Generated by Django 2.2 on 2019-04-24 06:06
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_superuser(apps, schema_editor):
    user = apps.get_model('auth', 'User')
    user.objects.create(
        username='admin',
        email='stanislav.dev3@gmail.com',
        password=make_password('admin!@#$%^&'),
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
